TrainingMVC/Models/Book.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace TrainingMVC.Models
{
    public class Book
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        [BsonElement("Name")]
        public string BookName { get; set; }

        [BsonElement]
        public decimal Price { get; set; }

        [BsonElement]
        public string Category { get; set; }

        [BsonElement]
        public string Author { get; set; }

    }
}

TrainingMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using TrainingMVC.Command.Book;
using TrainingMVC.Dtos;
using TrainingMVC.Query.Book;
using TrainingMVC.Query.Category;

namespace TrainingMVC.Controllers
{
    public class BookController : Controller
    {
        private IToastNotification _toastNotification;
        private IMediator _mediator;
        private IHttpClientFactory _httpClientFactory;

        public BookController(IMediator mediator, IToastNotification toastNotification, IHttpClientFactory httpClientFactory)
        {
            _mediator = mediator;
            _toastNotification = toastNotification;
            _httpClientFactory = httpClientFactory;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            var accessToken = await GetAccessToken();

            dynamic bookDtos = await _mediator.Send(new GetAllBookQuery(page ?? 1, accessToken));

            if (((List<BookDto>)bookDtos.books).Count == 0)
            {
                bookDtos = await _mediator.Send(new GetAllBookQuery((int)--page, accessToken));

            }
            ViewBag.totalPage = (int)bookDtos.totalPages;
            ViewBag.currentPage = page ?? 1;

            //await RefreshToken();


            return View((List<BookDto>)bookDtos.books);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            var accessToken = await GetAccessToken();

            var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
            var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, new BookDto());
            return View(tuple);
        }

        [HttpPost]
        public async Task<IActionResult> Insert([Bind(Prefix = "Item2")] BookDto bookDto)
        {
            var accessToken = await GetAccessToken();

            switch (ModelState.IsValid)
            {
                case true:
                    var response = await _mediator.Send(new NewBookCommand(bookDto, accessToken));
                    _toastNotification.AddSuccessToastMessage("Added Book");
                    return RedirectToAction(nameof(Index));
                case false:
                    var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
                    var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, new BookDto());
                    return View(tuple);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var accessToken = await GetAccessToken();

            var bookDto = await _mediator.Send(new GetByIdBookQuery(id, accessToken));
            if (bookDto == null)
            {
                return NotFound();
            }

            var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
            var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, bookDto);
            return View(tuple);
        }

        [HttpPost]
        public async Task<IActionResult> Update([Bind(Prefix = "Item2")] BookDto bookDto)
        {
            var accessToken = await GetAccessToken();

            switch (ModelState.IsValid)
            {
                case true:
                    var response = await _mediator.Send(new UpdateBookCommand(bookDto, bookDto.Id, accessToken));
                    _toastNotification.AddSuccessToastMessage("Updated Book");
                    return RedirectToAction("Index");
                case false:
                    var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
                    var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, bookDto);
                    return View(tuple);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int page, string id)
        {
            var accessToken = await GetAccessToken();

            var currentPage = page;
            var response = await _mediator.Send(new DeleteBookCommand(id, accessToken));
            _toastNotification.AddSuccessToastMessage("Removed Book");
            return RedirectToAction("Index", new { page = currentPage });
        }

        public async Task<string> GetIdToken()
        {
            return await HttpContext.GetTokenAsync("id_token");
        }

        public async Task<string> GetAccessToken()
        {
            return await HttpContext.GetTokenAsync("access_token");
        }

        public async Task<string> GetRefreshToken()
        {
            return await HttpContext.GetTokenAsync("refresh_token");
        }

        public async Task RefreshToken()
        {
            var serverClient = _httpClientFactory.CreateClient();
            var discoveryDocument = await serverClient.GetDiscoveryDocumentAsync("https://localhost:7001");

            var refreshToken = await GetRefreshToken();
            var refreshTokenClient = _httpClientFactory.CreateClient();

            var tokenResponse = await refreshTokenClient.RequestRefreshTokenAsync(new RefreshTokenRequest
            {
                Address = discoveryDocument.TokenEndpoint,
                ClientId = "client_id_mvc,",
                ClientSecret = "client_secret_mvc",
                GrantType = "refresh_token",
                RefreshToken = refreshToken,
            });

            var authInfo = await HttpContext.AuthenticateAsync("Cookie");

            authInfo.Properties.UpdateTokenValue("id_token", tokenResponse.IdentityToken);
            authInfo.Properties.UpdateTokenValue("access_token", tokenResponse.AccessToken);
            authInfo.Properties.UpdateTokenValue("refresh_token", tokenResponse.RefreshToken);

            await HttpContext.SignInAsync("Cookie", authInfo.Principal, authInfo.Properties);




        }



    }
}

TrainingMVC/Views/Book/Index.cshtml
@model List<TrainingMVC.Dtos.BookDto>

<div class="container">
    <div class="row">
        <div class="col s12">
            <h1 class="center-align grey-text text-darken-4">List of Books</h1>
        </div>
    </div>

    <br />
    <br />

    <div class="row">
        <div class="col s12">
            <a asp-controller="Book" asp-action="Insert" class="waves-effect red lighten-1 btn">
                <i class="material-icons right">add</i>
                Add New Book
            </a>
        </div>
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        My Books List
                    </span>
                    <div class="table-responsive">
                        <table class="highlight">
                            <thead>
                                <tr>
                                    <td>Book Id</td>
                                    <td>Book Name</td>
                                    <td>Book Author</td>
                                    <td>Price</td>
                                    <td>Category</td>
                                    <td colspan="2" style="text-align:center">
                                        <h6>Action</h6>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var book in Model)
                                {
                                    <tr>
                                        <td>@book.Id</td>
                                        <td>@book.BookName</td>
                                        <td>@book.Author</td>
                                        <td>@book.Price</td>
                                        <td>@book.Category</td>
                                        <td>
                                            @*<a class="waves-effect red-text text-lighten-1" asp-controller="Book" asp-action="Update"
                                                asp-route-id="@book.Id">Edit</a>*@
                                            @Html.ActionLink("Edit", "Update", "Book", new { id = book.Id }, new { @class = "waves-effect red-text text-lighten-1" })
                                        </td>
                                        <td>
                                            @*<a class="waves-effect red-text text-lighten-1" asp-controller="Book" asp-action="Delete"
                                                asp-route-id="@book.Id">Delete</a>*@
                                            @Html.ActionLink("Remove", "Delete", "Book", new { id = book.Id, page = ViewBag.currentPage }, new { @class = "waves-effect red-text text-lighten-1" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="col s12">
                        <partial name="_Paging" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TrainingMVC/Views/Book/Insert.cshtml
@using TrainingMVC.Dtos;
@model Tuple<List<CategoryDto>, BookDto>
<div class="container">

    <div class="row">
        <div class="col s12">
            <h1 class="center-align grey-text text-darken-4">Add New Book</h1>
        </div>
    </div>

    <br />
    <br />

    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form id="insertForm" asp-controller="Book" asp-action="Insert"
                          method="post">
                        <div class="row">
                            <div class="input-field col s12">
                                <input asp-for="@Model.Item2.BookName">
                                @*<label>Book Name</label>*@
                                @Html.LabelFor(m => m.Item2.BookName)
                                <span asp-validation-for="@Model.Item2.BookName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input asp-for="@Model.Item2.Author">
                                @*<label>Book Author</label>*@
                                @Html.LabelFor(m => m.Item2.Author)
                                <span asp-validation-for="@Model.Item2.Author" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <input asp-for="@Model.Item2.Price">
                                @*<label>Price</label>*@
                                @Html.LabelFor(m => m.Item2.Price)
                                <span asp-validation-for="@Model.Item2.Price" class="text-danger"></span>
                            </div>
                            <div class="input-field col s6">
                                <select asp-for="@Model.Item2.Category">
                                    <option value="" selected>Choose category</option>
                                    @foreach (var category in Model.Item1)
                                    {
                                        <option value=@category.CategoryName>@category.CategoryName</option>
                                    }
                                </select>
                                <span asp-validation-for="@Model.Item2.Category" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12 center-align">
                                <button class="btn waves-effect red lighten-1" type="submit" name="action">
                                    Save
                                    <i class="material-icons right">send</i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

TrainingMVC/Views/Book/Update.cshtml
@using TrainingMVC.Dtos;
@model Tuple<List<CategoryDto>, BookDto>


    <div class="container">

        <div class="row">
            <div class="col s12">
                <h1 class="center-align grey-text text-darken-4">Update Book</h1>
            </div>
        </div>

        <br />
        <br />


        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <form asp-controller="Book" asp-action="Update"
                              method="post">
                            <div class="row">
                                <div class="input-field col s12">
                                    <input asp-for="@Model.Item2.Id" readonly value="@Model.Item2.Id">
                                    <label>Book Id</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input asp-for="@Model.Item2.BookName" value="@Model.Item2.BookName">
                                    @*<label>Book Name</label>*@
                                    @Html.LabelFor(m => m.Item2.BookName)
                                    <span asp-validation-for="@Model.Item2.BookName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input asp-for="@Model.Item2.Author" value="@Model.Item2.Author">
                                    @*<label>Book Author</label>*@
                                    @Html.LabelFor(m => m.Item2.Author)
                                    <span asp-validation-for="@Model.Item2.Author" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s6">
                                    <input asp-for="@Model.Item2.Price" value="@Model.Item2.Price">
                                    @*<label>Price</label>*@
                                    @Html.LabelFor(m => m.Item2.Price)
                                    <span asp-validation-for="@Model.Item2.Price" class="text-danger"></span>
                                </div>
                                <div class="input-field col s6">
                                    <select asp-for="@Model.Item2.Category">
                                        @foreach (var category in Model.Item1)
                                        {
                                            @*TagHelper doesn't allows C# code in their tag area.
                                                turn an option element into a regular html tag by using the character !.*@
                                            <option value=@category.CategoryName>
                                                @category.CategoryName
                                            </option>
                                        }
                                    </select>
                                    <span asp-validation-for="@Model.Item2.Category" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col s12 center-align">
                                    <button class="btn waves-effect red lighten-1" type="submit" name="action">
                                        Update
                                        <i class="material-icons right">send</i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>