TrainingMVC/Models/User.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TrainingMVC.Models
{
    public class User
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

TrainingMVC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using TrainingMVC.Command.Book;
using TrainingMVC.Dtos;
using TrainingMVC.Query.Book;
using TrainingMVC.Query.Category;

namespace TrainingMVC.Controllers
{
    public class BookController : Controller
    {
        private IToastNotification _toastNotification;
        private IMediator _mediator;
        private IHttpClientFactory _httpClientFactory;

        public BookController(IMediator mediator, IToastNotification toastNotification, IHttpClientFactory httpClientFactory)
        {
            _mediator = mediator;
            _toastNotification = toastNotification;
            _httpClientFactory = httpClientFactory;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            var accessToken = await GetAccessToken();

            dynamic bookDtos = await _mediator.Send(new GetAllBookQuery(page ?? 1, accessToken));

            if (((List<BookDto>)bookDtos.books).Count == 0)
            {
                bookDtos = await _mediator.Send(new GetAllBookQuery((int)--page, accessToken));

            }
            ViewBag.totalPage = (int)bookDtos.totalPages;
            ViewBag.currentPage = page ?? 1;

            //await RefreshToken();


            return View((List<BookDto>)bookDtos.books);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Insert()
        {
            var accessToken = await GetAccessToken();

            var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
            var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, new BookDto());
            return View(tuple);
        }

        [HttpPost]
        public async Task<IActionResult> Insert([Bind(Prefix = "Item2")] BookDto bookDto)
        {
            var accessToken = await GetAccessToken();

            switch (ModelState.IsValid)
            {
                case true:
                    var response = await _mediator.Send(new NewBookCommand(bookDto, accessToken));
                    _toastNotification.AddSuccessToastMessage("Added Book");
                    return RedirectToAction(nameof(Index));
                case false:
                    var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
                    var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, new BookDto());
                    return View(tuple);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var accessToken = await GetAccessToken();

            var bookDto = await _mediator.Send(new GetByIdBookQuery(id, accessToken));
            if (bookDto == null)
            {
                return NotFound();
            }

            var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
            var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, bookDto);
            return View(tuple);
        }

        [HttpPost]
        public async Task<IActionResult> Update([Bind(Prefix = "Item2")] BookDto bookDto)
        {
            var accessToken = await GetAccessToken();

            switch (ModelState.IsValid)
            {
                case true:
                    var response = await _mediator.Send(new UpdateBookCommand(bookDto, bookDto.Id, accessToken));
                    _toastNotification.AddSuccessToastMessage("Updated Book");
                    return RedirectToAction("Index");
                case false:
                    var categoryDtos = await _mediator.Send(new GetAllCategoryQuery(accessToken));
                    var tuple = new Tuple<List<CategoryDto>, BookDto>(categoryDtos, bookDto);
                    return View(tuple);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int page, string id)
        {
            var accessToken = await GetAccessToken();

            var currentPage = page;
            var response = await _mediator.Send(new DeleteBookCommand(id, accessToken));
            _toastNotification.AddSuccessToastMessage("Removed Book");
            return RedirectToAction("Index", new { page = currentPage });
        }

        public async Task<string> GetIdToken()
        {
            return await HttpContext.GetTokenAsync("id_token");
        }

        public async Task<string> GetAccessToken()
        {
            return await HttpContext.GetTokenAsync("access_token");
        }

        public async Task<string> GetRefreshToken()
        {
            return await HttpContext.GetTokenAsync("refresh_token");
        }

        public async Task RefreshToken()
        {
            var serverClient = _httpClientFactory.CreateClient();
            var discoveryDocument = await serverClient.GetDiscoveryDocumentAsync("https://localhost:7001");

            var refreshToken = await GetRefreshToken();
            var refreshTokenClient = _httpClientFactory.CreateClient();

            var tokenResponse = await refreshTokenClient.RequestRefreshTokenAsync(new RefreshTokenRequest
            {
                Address = discoveryDocument.TokenEndpoint,
                ClientId = "client_id_mvc,",
                ClientSecret = "client_secret_mvc",
                GrantType = "refresh_token",
                RefreshToken = refreshToken,
            });

            var authInfo = await HttpContext.AuthenticateAsync("Cookie");

            authInfo.Properties.UpdateTokenValue("id_token", tokenResponse.IdentityToken);
            authInfo.Properties.UpdateTokenValue("access_token", tokenResponse.AccessToken);
            authInfo.Properties.UpdateTokenValue("refresh_token", tokenResponse.RefreshToken);

            await HttpContext.SignInAsync("Cookie", authInfo.Principal, authInfo.Properties);




        }



    }
}

TrainingMVC/Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TrainingMVC.Dtos;
using Microsoft.AspNetCore.Http;
using NToastNotify;
using MediatR;
using TrainingMVC.Query.User;

namespace TrainingMVC.Controllers
{
    public class LoginController : Controller
    {
        private IMediator _mediator;
        private IToastNotification _toastNotification;
        public LoginController(IToastNotification toastNotification, IMediator mediator)
        {
            _toastNotification = toastNotification;
            _mediator = mediator;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserDto userDto)
        {
            if (ModelState.IsValid)
            {
                var login = await _mediator.Send(new AuthenUserQuery(userDto));
                if (!login)
                {
                    //ModelState.AddModelError("", "The User name or password is incorrect");
                    _toastNotification.AddErrorToastMessage("The User name or password is incorrect");
                    return View();
                }
                HttpContext.Session.SetString("username", userDto.UserName);
                return RedirectToAction("Index", "Book");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToRoute(new
            {
                controller = "Book",
                action = "Index"
            });
        }
    }
}

TrainingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrainingMVC</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="nav-extended red lighten-1">
            <div class="container">
                <div class="nav-wrapper">
                    <a class="brand-logo grey-text text-lighten-5" asp-controller="/" asp-action="Index">MVC</a>
                    @*<partial name="_User" />*@
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TrainingMVC - <a asp-area="" asp-controller="Book" asp-action="Index">Home</a>
        </div>
    </footer>
    @await Component.InvokeAsync("NToastNotify")
</body>
</html>

TrainingMVC/Views/Shared/_Paging.cshtml
<ul class="pagination">
    @if (ViewBag.currentPage > 1)
    {
        <li class="waves-effect">
            <a asp-controller="Book" asp-action="Index"
               asp-route-page="@(ViewBag.currentPage - 1)">
                <i class="material-icons">chevron_left</i>
            </a>
        </li>
    }
    else
    {
        <li class="disabled">
            <a><i class="material-icons">chevron_left</i></a>
        </li>
    }
    @{
        var currentPage = (int)ViewBag.currentPage;
        var totalPage = (int)ViewBag.totalPage;

        const int PageLeft = 2;
        const int PagesRight = 2;

        var fromPage = Math.Max(1, currentPage - PageLeft);

        var toPage = Math.Min(totalPage, currentPage + PagesRight);

        if (totalPage - toPage == 1)
        {
            toPage = totalPage;
        }

        if (fromPage > 1)
        {
            <li class="waves-effect">
                <a asp-controller="Book" asp-action="Index"
                   asp-route-page="1">
                    1
                </a>
            </li>

            if (fromPage > 2)
            {
                var middlePage = (int)Math.Ceiling((double)((fromPage + 1) / 2));
                <li class="waves-effect">
                    <a asp-controller="Book" asp-action="Index"
                       asp-route-page="@middlePage">
                        ...
                    </a>
                </li>
            }
        }

        for (int i = fromPage; i <= toPage; i++)
        {
            <li class="@(ViewBag.currentPage == i ? "active" : "waves-effect" )">
                <a asp-controller="Book" asp-action="Index" asp-route-page="@i">@i</a>
            </li>
        }

        if (toPage < totalPage)
        {
            int middlePage = (int)Math.Floor((double)((totalPage + toPage) / 2));
            <li class="waves-effect">
                <a asp-controller="Book" asp-action="Index"
                   asp-route-page="@middlePage">
                    ...
                </a>
            </li>
            if (toPage < totalPage - 1)
            {
                <li class="waves-effect">
                    <a asp-controller="Book" asp-action="Index"
                       asp-route-page="@totalPage">
                        @totalPage
                    </a>
                </li>
            }
        }
    }

    @if (ViewBag.currentPage < ViewBag.totalPage)
    {
        <li class="waves-effect">
            <a asp-controller="Book" asp-action="Index"
               asp-route-page="@(ViewBag.currentPage + 1)">
                <i class="material-icons">chevron_right</i>
            </a>
        </li>
    }
    else
    {
        <li class="disabled">
            <a><i class="material-icons">chevron_right</i></a>
        </li>
    }
</ul>

TrainingMVC/Views/Shared/_user.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    if (HttpContextAccessor.HttpContext.Session.GetString("username") == null)
    {
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
                <a class="grey-text text-lighten-5" asp-controller="Login" asp-action="Login">
                    Login
                    <i class="material-icons left">login</i>
                </a>
            </li>
        </ul>
    }
    else
    {
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
                <a class="grey-text text-lighten-5" asp-controller="Login" asp-action="Logout">
                    Logout
                    <i class="material-icons left">logout</i>
                </a>
            </li>
        </ul>
    }
}